### ISSUE TITLE
Variable assigned but never read - PROPERTY default access modifier

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#637]
Hello,

Version: 2.2.6
Sonarlint: 3.6.1006

The rule "Variable assigned but never read" doesn't work for Properties with the default access modifier.

Default Access Modifier:
Variable: PRIVATE
Property: PUBLIC

![property-default](https://user-images.githubusercontent.com/39283158/51307979-599a6d80-1a41-11e9-8599-b7f8ca89b274.png)
![property-public](https://user-images.githubusercontent.com/39283158/51307983-5d2df480-1a41-11e9-8f2e-a2e0761ba466.png)

**Comment by gquerret** [comment]
Similar to #547.
Was fixed in UnusedVariable, but not in the related rules. What was the rule developer thinking about ?? 😠

**Comment by gquerret** [comment]
Merged in develop

**Comment by lneumeier** [comment]
I updated our Sonarqube instance zu 2.3.0, but PDSOE is still on 1006 version and did a refresh in the sonarqube servers view, but this problem is still there. I assume this is not fixed in 2.3.0?

**Comment by gquerret** [comment]
SLint version doesn't matter here. Fix should be included in 2.3.0. Did you execute "Update local bindings" in SLint ?

**Comment by lneumeier** [comment]
Yes, I did.
![sonar1](https://user-images.githubusercontent.com/39283158/51478953-321f0a00-1d8d-11e9-8e4a-88f38517eb3d.png)
![sonar2](https://user-images.githubusercontent.com/39283158/51478957-3519fa80-1d8d-11e9-90e5-04334cfd7fc8.png)
![sonar3](https://user-images.githubusercontent.com/39283158/51478962-3814eb00-1d8d-11e9-8be1-5360808d1340.png)

**Comment by gquerret** [comment]
Fixed again in develop, a case wasn't correctly trapped
