### ISSUE TITLE
XREF XML contains invalid characters and log error messages

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#87]
If souce code contains strings with 'invalid' characters (0x01 for example), then XML files become malformed. When parsed by the plugin, they generate log messages, and no info can be imported.

```
11:21:52 [sonar:sonar] [Fatal Error] vcustomer.w.xref:697:73: Ungültiges XML-Zeichen (Unicode: 0x4) wurde im Wert des Attributs "Object-identifier" gefunden. Element ist "Reference".
11:21:52 [sonar:sonar] Unable to parse file E:\Jenkins\workspace\xxxx-64SonarSource\build\.pct\OERA\visual\vcustomer.w.xref
11:21:52 [sonar:sonar] org.xml.sax.SAXParseException: Ungültiges XML-Zeichen (Unicode: 0x4) wurde im Wert des Attributs "Object-identifier" gefunden. Element ist "Reference".
11:21:52 [sonar:sonar]       at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) ~[na:1.8.0_111]
...
```

**Comment by gquerret** [comment]
Fixed in master

**Comment by maelstraggiotti** [comment]
I still encounter this error with 2.0.4-SNAPSHOT : 
```
[Fatal Error] :18646:59: An invalid XML character (Unicode: 0x8) was found in the value of attribute "Object-identifier" and element is "Reference".
```
Incriminated source code is : ```DEF VAR SepValCle AS C INITIAL "~008".```

**Comment by gquerret** [comment]
@maelstraggiotti Do you use property `sonar.oe.filter.invalidxref` ? See https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list
